### ISSUE TITLE
The intro seems to have been fully deleted

### ISSUE THREAD

**Issue by justdanielheart** [JackboxUtility/JackboxUtility#362]
For some reason now whenever I start the party pack 6 it will always go to the game I last opened with the utility and because I only used it once to try the utility out I tried it with push the button and it will always open push the button and it is kind of annoying because I really like the intros and while the utility is nice I don't plan on using it every time I mostly downloaded it just to patch some games to Spanish because most of my friends can't speak English regardless I tried the same with  party pack 10 unpatched and the same thing happened no intro supposedly it is not meant to delete the intro completely so please get me some help some sort of reset button that makes it go back to the normal intro would be good i also patched the pack 9 and kind of want to get it back to normal but don't really want to reinstall it so if there is a way to do that please tell me

**Comment by MeDustyy** [comment]
![image](https://github.com/JackboxUtility/JackboxUtility/assets/58863601/3ba0947c-faea-4ac9-9c6c-cd3935296d94)

**Comment by AkiraArtuhaxis** [comment]
Ya que veo que hablas español, redactaré la respuesta en español.
Si lo que deseas es restaurar los juegos a como estaban originalmente, ve a "Ajustes" y pulsa la pequeña flecha al lado de cada juego (en la captura encima mío se menciona dónde está). Los juegos se restaurarán a como estaban originalmente. También puedes verificar los archivos con Steam/EGS para solucionar el problema. La introducción se restaurará y los Party Packs comenzarán desde el menú y no directamente en un juego en específico.

**Comment by justdanielheart** [comment]
<img width="1470" alt="Captura de pantalla 2023-11-25 a las 18 39 49" src="https://github.com/JackboxUtility/JackboxUtility/assets/152024228/4d276ce3-ba68-4726-a1e3-cf72041e56eb">

**Comment by justdanielheart** [comment]
It doesn't appear maybe I got an old version?

**Comment by AkiraArtuhaxis** [comment]
Eso quiere decir que agregaste los juegos manualmente y no mediante la detección automática. Deberás verificar los archivos con Steam para solucionar el problema.
Para ello, en tu biblioteca de Steam debes hacer clic derecho en el juego que quieras restaurar, luego pulsas "Propiedades...", vas a "ARCHIVOS LOCALES" y finalmente pulsas "Verificar integridad de los archivos de juego...".
De todos modos, hiciste funcionar la Utility en Mac? Cómo?

**Comment by justdanielheart** [comment]
Tengo parallels desktop en mi Mac book así que puedo usar aplicaciones de windows (entre tú y yo suele costar bastante dinero pero encontré un tutorial para tenerlo gratis) de todos modos intentare hacer lo que me dijiste muchísimas gracias por tu ayuda lo aprecio mucho

**Comment by AkiraArtuhaxis** [comment]
Ya veo, así que emulaste la aplicación en Windows y funcionó perfectamente, interesante.
Para que sepas, se supone que la aplicación restaure el archivo de menú original una vez que la cierras (lo que hace que la introducción no se omita y no inicie directamente en un juego). Pero supongo que al estar emulando la aplicación eso no puede suceder. Cuando la aplicación tenga una versión nativa de Mac es probable que eso se solucione.
Si no es problema, te pediría que, si lo deseas, te unas a nuestro servidor de Discord para ayudar a probar la aplicación que funciona en Mac de manera nativa.

**Comment by justdanielheart** [comment]
Estaría bien unirme al discord para probarlo cuando salga no he conseguido que se me solucione con steam así que estoy reinstalando los juegos en los que he entrado de todos modos muchas gracias
