### ISSUE TITLE
Add the option to split a patch in multiple parts

### ISSUE THREAD

**Issue by DerErizzle** [JackboxUtility/JackboxUtility#365]
Since GitHub only allows to upload files up to 2 GB for releases, we need to split our patch in two parts. Jackbox Utility would need to download and install both zip files.

Maybe this can be done by allowing an array like this for the "patch_path" value like in the attached image.
![image](https://github.com/JackboxUtility/JackboxUtility/assets/43215958/d1cc693f-d09f-4f98-adf0-7e1180284d99)

**Comment by AkiraArtuhaxis** [comment]
I not exactly against this, but can't the two parts be uploaded as separate patches and be included in the "All patches" category?

**Comment by DerErizzle** [comment]
Not really, since we don't want to change the way the user would need to install their patches. And we're surpassing the 2 GB limit with our next PP5 update

**Comment by AkiraArtuhaxis** [comment]
Fair enough, although manually you're definitely changing the way a user installs this patch in particular anyways.
