### ISSUE TITLE
Create Shortcut Feature

### ISSUE THREAD

**Issue by MeDustyy** [JackboxUtility/JackboxUtility#370]
This future allows users to create a desktop shortcuts to the games.
Using the shortcut, users can launch games via Jackbox Utility, bypassing all unnecessary screens.
[Thanks to Akira for this idea :)](https://discord.com/channels/1108095925366308954/1108095925928329218/1199213048469135420)

Since I couldn't think of a better place for the "Create Shortcut" button, I suggest creating a "meatballs menu" like this↓ next to the Launch button.
- Before:
![menu1](https://github.com/JackboxUtility/JackboxUtility/assets/58863601/8307a64d-e2ec-468a-b41d-d42e01a532aa)
- After:
![menu2](https://github.com/JackboxUtility/JackboxUtility/assets/58863601/d4137472-518e-4548-93dd-c4ec951917ce)
- Menu active:
![menu3](https://github.com/JackboxUtility/JackboxUtility/assets/58863601/641c4edd-f588-4016-b0da-502fab22e682)

**Comment by AkiraArtuhaxis** [comment]
[I already suggested this feature.](https://github.com/JackboxUtility/JackboxUtility/issues/367)
Also, I'm not really sure about that dropdown menu. It looks kinda odd.

**Comment by MeDustyy** [comment]
> I already suggested this feature.

Oops, sorry. I didn't see that.
