### ISSUE TITLE
Default loaders not restoring

### ISSUE THREAD

**Issue by AkiraArtuhaxis** [JackboxUtility/JackboxUtility#385]
At the moment, the default loaders are not restoring after closing the Utility. When you open a game normally without using the Utility, the last game you launched will open.

**Comment by choke-dev** [comment]
https://github.com/JackboxUtility/JackboxUtility/assets/47597850/d351d283-23a1-41cf-85b1-caf202194331

can confirm this

**Comment by AkiraArtuhaxis** [comment]
For reference, this is the version where the default loaders start to not restore: https://github.com/JackboxUtility/JackboxUtility/releases/tag/1.3.6%2B3-beta-1700430005
And this is the last version where the default loaders do restore: https://github.com/JackboxUtility/JackboxUtility/releases/tag/1.3.6%2B3-beta-1700427626
