### ISSUE TITLE
YDKJ 2015 has zero progress when launched through Jackbox Utility

### ISSUE THREAD

**Issue by AintSoSunny** [JackboxUtility/JackboxUtility#387]
No game progress is destroyed, thankfully, but when launched through Jackbox Utility, all game unlocks and scores are reset.

**Comment by AkiraArtuhaxis** [comment]
Weird. For me, it's the other way around. The game has progress when launched through the Utility, but doesn't when launched using the Party Pack.
I think this implies that for whatever reason each type of launching has its separate save file.
This can may be fixed, but I really doubt it will.
