### ISSUE TITLE
Unable to auto-detect Steam games for MacOS app

### ISSUE THREAD

**Issue by seferino-fernandez** [JackboxUtility/JackboxUtility#393]
I cloned the branch and I ran the app using the beta flavor and I got the below error message. It seems like the [relative file path being used for MacOS](https://github.com/JackboxUtility/JackboxUtility/blob/dev/jackbox_patcher/lib/services/automaticGameFinder/AutomaticGameFinder.dart#L57) isn't getting resolved. 

```dart
flutter: [I] TIME: 2024-05-01T13:40:41.748582 Looking for Steam games
flutter: [I] TIME: 2024-05-01T13:40:41.748741 Steam location: ~/Library/Application Support/Steam
flutter: #0   AutomaticGameFinderService.findGames (package:jackbox_patcher/services/automaticGameFinder/AutomaticGameFinder.dart:27:20)
flutter: #1   <asynchronous suspension>
flutter: 13:40:41.751 (+0:00:02.433660)
flutter: ⛔ PathNotFoundException: Cannot open file, path = '~/Library/Application Support/Steam/steamapps/libraryfolders.vdf' (OS Error: No such file or directory, errno = 2)
```

I was able to fix it locally by using the `Platform.environment["HOME"]` function for the MacOS Steam location path.
`steamLocation = "${Platform.environment["HOME"]!}/Library/Application Support/Steam";`

Git: dev - 09f34683580f650dfc3362a8552ba3379ee3726e
Apple M2 Pro
MacOS Sonoma 14.4.1

**Comment by AlexisL61** [comment]
Hello @seferino-fernandez 

Thank you for your contribution! I merged your changes.
As I don't have a Mac myself, there might be more bugs hiding using this device. In case you find one, feel free to open an issue!

**Comment by AlexisL61** [comment]
@all-contributors please add @seferino-fernandez for bug and code

**Comment by AlexisL61** [comment]
@all-contributors please add @seferino-fernandez for bug and code
