### ISSUE TITLE
Error when attempting to run JackboxUtility

### ISSUE THREAD

**Issue by Trey-Daviz** [JackboxUtility/JackboxUtility#397]
![image](https://github.com/JackboxUtility/JackboxUtility/assets/77282503/29bc4e0f-5f3a-4f71-a1c3-45d19501eaf5)
This is the error I got when I tried to run the Jackbox Utility file.  I did not do anything fancy.  I just downloaded it, unzipped it, then tried to run it.  It failed immediately.

**Comment by AlexisL61** [comment]
Hello @Trey-Daviz 
It seems that you didn't extract the whole zip. You must extract all the content of the zip in a folder and then run the JackboxUtility.exe in this folder to start the application

**Comment by DerErizzle** [comment]
This error message means that you need to install [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
