### ISSUE TITLE
Party Pack 6 Gets Stuck on a Black Screen. 

### ISSUE THREAD

**Issue by ShaggersHot** [JackboxUtility/JackboxUtility#399]
Whenever I Put my Copy of Party Pack 6 onto Jackbox Utility Manually, as I Have to do with a Non Steam Copy, and Open a Game from it, it Stays on a Black Screen in Windowed Mode. This Issue has Happened Both with Me and a Friend of Mine, and is the Only Pack this Happens with. After Putting the Pack on Jackbox Utility, even Launching the Pack from its EXE has the Same Issue. This Started about a Month Ago for me. My Party Pack 6 is on v456, and the Same Thing Happens when I Try Putting it as the Epic Games Version Aswell. 
![Screenshot 2024-07-26 224111](https://github.com/user-attachments/assets/e8d9b5c4-6349-492f-9072-e80a6e18d4b7)

**Comment by AkiraArtuhaxis** [comment]
Your version is outdated and most likely pirated. These are not and will not be supported. The Epic Games Store version should work as long as either is detected automatically by the Utility or you add it manually selecting the specific EGS version ("The Jackbox Party Pack 6 [Epic Games]".
