### ISSUE TITLE
Megapicker broke Utility

### ISSUE THREAD

**Issue by RegDuy** [JackboxUtility/JackboxUtility#400]
Please fix this ASAP!!!! Jackbox updated all their packs when the Megapicker came out and as such broke compatibility with Utility

**Comment by AlexisL61** [comment]
Hello @RegDuy, a fix is coming really soon with the new way to launch games on Steam. Keep in mind that we are a team of volunteers working on our free time so it can take some time to update the app

**Comment by JBG-brad** [comment]
Hey @AlexisL61 can you reach out to me via Eric A?

I'd like to better understand how our changes broke Jackbox Utility. 

It certainly wasn't our intention.

**Comment by AlexisL61** [comment]
The fix should be done on develop.

Some informations about it:
- By default, the games on Steam will launch without the loaders (using the -launchTo argument). But the games on Epic Games and added manually will still launch using a loader.
- Each server owner can customize how the game is launched for each game and each platform independently using the packs.json file. That way, if the new way to launch games doesn't work, you can still use the old loaders.

For server owners:
- Each game now need to have an internal_name like this (with this, it can be launched with the new launcher feature) :
```json
"game" : {
  ...
  "internal_name": "Auction"
  ...
}
```
 
To change the behavior of how a game is launched, you can use this in a game :
```json
game: {
  ...
  "launch_with_loaders" : {
    "steam": false,
    "epic_games": true,
    "native": true
  }
  ...
}
```

**Comment by AlexisL61** [comment]
The 1.4.0 is now live. I will close this issue and reopen it in case there are some bugs in this release
