### ISSUE TITLE
Suggestion: retry download button

### ISSUE THREAD

**Issue by ACertainCoder** [JackboxUtility/JackboxUtility#401]
The Jackbox Utility currently displays an error message if a download failed for some reason, with the only option being to cancel the download completely. Instead it would be useful if there were a second "retry" button. The app should then attempt to continue without throwing away the part that had been downloaded so far.

**Comment by ACertainCoder** [comment]
On that note, it would also be handy if the Jackbox Utility would start retry attempts by itself a few times (e.g. 10), possibly with a pause inbetween those attempts (e.g. 60s).

**Comment by AlexisL61** [comment]
I don't think it is a good idea to retry automatically (if it doesn't work the first time, then it will mostly not work the second time).
I agree with the retry button, and I think it should come with additional information about the error.

**Comment by ACertainCoder** [comment]
In my case, the app sometimes seems to cancel the download due to my slow Internet connection. If I restart the download, it works just fine again.

**Comment by AlexisL61** [comment]
> In my case, the app sometimes seems to cancel the download due to my slow Internet connection. If I restart the download, it works just fine again.

Alright, I see. I think the retry button is the best right here even for your case instead of the automatic retry attempts
