### ISSUE TITLE
Crash on windows on latest version

### ISSUE THREAD

**Issue by AlexisL61** [JackboxUtility/JackboxUtility#407]
2 users crashed when they entered the "Launch games" section on windows.

They were all on Windows 10.

One of them fixed it by downloading the necessary tools to build a flutter project. 

I was able to reproduce the issue using a fresh Windows installation in a VM. I have created a dump of the crash and the problem seems related to a dll called msvcp140.dll.

This dll was also the reason of removal from the library we used for the videos called media_kit as it added the dll in the folder of the app.

What I suppose is :
- media_kit was using an old version of the dll and that's why it crashed
- Flutter use the .dll in its folder in priority before searching for an installed .dll
- That means that the users with the crashes have an outdated msvcp140.dll on their computer
- Adding the latest msvcp140.dll in the app folder should fix the problem

**Comment by AlexisL61** [comment]
Related to #400 and #406

**Comment by AlexisL61** [comment]
@all-contrbutors please add @jWalker92 for testing

**Comment by AlexisL61** [comment]
@all-contributors please add @jWalker92 for tests

**Comment by MisterAlexEsquire** [comment]
This may just be a rehash of existing user reports, but here is the content of the Error that is logged in my Event Viewer:

> Faulting application name: jackbox_patcher.exe, version: 1.4.0.0, time stamp: 0x66b12fe2
> Faulting module name: MSVCP140.dll, version: 14.31.31103.0, time stamp: 0xf632f325
> Exception code: 0xc0000005
> Fault offset: 0x00000000000132a8
> Faulting process id: 0x2204
> Faulting application start time: 0x01daecff5d74b924
> Faulting application path: C:\Users\User\Downloads\JackboxUtility_Windows-140\jackbox_patcher.exe
> Faulting module path: C:\Windows\SYSTEM32\MSVCP140.dll
> Report Id: bdf6f528-8f27-4744-b03b-25ff387baf2a
> Faulting package full name: 
> Faulting package-relative application ID: 

Windows 10 Home x64

**Comment by MisterAlexEsquire** [comment]
I went ahead and grabbed the [latest x64 vc redist package](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) from Microsoft and installed it.
Jackbox Utility no longer crashes at startup for me.

**Comment by AlexisL61** [comment]
Yes, we will have to add the latest version of MSVCP140.dll in the next release. Thank you for the dump!

**Comment by AlexisL61** [comment]
Should be fixed in the 1.4.1. Will reopen if the problem persists
